"""End-to-end tests — fake claude executable, full dispatch→integrate flow."""

from __future__ import annotations

import asyncio
import json
import os
import subprocess
import sys
import textwrap
from pathlib import Path
from unittest.mock import patch

import pytest

from cagent.tasks import Task, dump_state, parse_tasks_file


_FAKE_CLAUDE_SCRIPT = textwrap.dedent('''\
    """Fake claude -p that reads stdin prompt and writes a file in CWD."""
    import json, os, sys

    prompt = sys.stdin.read()
    # Emit stream-json init
    print(json.dumps({"type": "system", "subtype": "init", "model": "fake-model"}))
    sys.stdout.flush()

    # Write a file based on the task — the file name is derived from the prompt
    # Convention: prompt contains "FILE:<name>" to tell us what to create
    import re
    m = re.search(r"FILE:(\\S+)", prompt)
    if m:
        filepath = m.group(1)
        os.makedirs(os.path.dirname(filepath), exist_ok=True) if os.path.dirname(filepath) else None
        with open(filepath, "w") as f:
            f.write(f"# generated by task\\n# prompt: {prompt[:50]}\\n")

    # Emit result
    print(json.dumps({
        "type": "result",
        "subtype": "success",
        "usage": {"input_tokens": 100, "output_tokens": 50}
    }))
    sys.stdout.flush()
''')

_FAKE_CLAUDE_NOOP = textwrap.dedent('''\
    """Fake claude that does nothing (for noop test)."""
    import json, sys
    sys.stdin.read()
    print(json.dumps({"type": "system", "subtype": "init", "model": "fake-model"}))
    print(json.dumps({"type": "result", "subtype": "success", "usage": {"input_tokens": 10, "output_tokens": 5}}))
''')

_FAKE_CLAUDE_FAIL = textwrap.dedent('''\
    """Fake claude that exits with error."""
    import json, sys
    sys.stdin.read()
    print(json.dumps({"type": "system", "subtype": "init", "model": "fake-model"}))
    print(json.dumps({"type": "result", "subtype": "error", "usage": {"input_tokens": 10, "output_tokens": 5}}))
    sys.exit(1)
''')


@pytest.fixture
def fake_claude(tmp_path: Path) -> Path:
    """Create a fake claude script that writes files based on prompt."""
    script = tmp_path / "fake_claude.py"
    script.write_text(_FAKE_CLAUDE_SCRIPT, encoding="utf-8")
    return script


@pytest.fixture
def fake_claude_noop(tmp_path: Path) -> Path:
    script = tmp_path / "fake_claude_noop.py"
    script.write_text(_FAKE_CLAUDE_NOOP, encoding="utf-8")
    return script


@pytest.fixture
def fake_claude_fail(tmp_path: Path) -> Path:
    script = tmp_path / "fake_claude_fail.py"
    script.write_text(_FAKE_CLAUDE_FAIL, encoding="utf-8")
    return script


@pytest.fixture
def e2e_repo(tmp_path: Path) -> Path:
    """Create a minimal git repo for e2e testing."""
    from cagent.agent import _CAGENT_GITIGNORE_MARKER, _CAGENT_GITIGNORE_LINES

    repo = tmp_path / "repo"
    repo.mkdir()
    subprocess.run(["git", "init"], cwd=repo, capture_output=True, check=True)
    subprocess.run(
        ["git", "config", "user.email", "test@e2e.com"],
        cwd=repo, capture_output=True, check=True,
    )
    subprocess.run(
        ["git", "config", "user.name", "E2E Test"],
        cwd=repo, capture_output=True, check=True,
    )
    (repo / "README.md").write_text("# E2E test repo\n", encoding="utf-8")
    # Include .gitignore with cagent marker to prevent agent from creating it
    (repo / ".gitignore").write_text(
        f"{_CAGENT_GITIGNORE_MARKER}\n{_CAGENT_GITIGNORE_LINES}",
        encoding="utf-8",
    )
    subprocess.run(["git", "add", "."], cwd=repo, capture_output=True, check=True)
    subprocess.run(
        ["git", "commit", "-m", "initial"],
        cwd=repo, capture_output=True, check=True,
    )
    return repo


def _resolve_claude_to(script_path: Path) -> str:
    """Return the python command to run the fake script."""
    return str(script_path)


@pytest.mark.asyncio
async def test_e2e_two_tasks_no_deps(e2e_repo: Path, fake_claude: Path) -> None:
    """Two independent tasks → both commit → integration branch."""
    from cagent.dispatcher import run as dispatch_run
    from cagent.integrator import integrate
    from cagent.memory import RunMemory
    from cagent.progress import Dashboard
    from cagent.worktree import current_head

    run_dir = e2e_repo / ".cagent" / "runs" / "e2e-test-1"
    run_dir.mkdir(parents=True)

    base_sha = current_head(e2e_repo)

    tasks = [
        Task(id="001", prompt="Create module A FILE:module_a.py", branch="cagent/e2e-test-1/task-001"),
        Task(id="002", prompt="Create module B FILE:module_b.py", branch="cagent/e2e-test-1/task-002"),
    ]
    dump_state(run_dir, tasks)

    dashboard = Dashboard(run_dir)
    memory = RunMemory(run_dir)

    orig_exec = asyncio.create_subprocess_exec

    async def patched_exec(*args, **kwargs):
        args_list = list(args)
        if args_list and args_list[0] == "claude":
            args_list = [sys.executable, str(fake_claude)]
        return await orig_exec(*args_list, **kwargs)

    with patch("cagent.agent._resolve_claude", return_value="claude"), \
         patch("cagent.agent.prepare_sandbox"), \
         patch("cagent.agent.asyncio.create_subprocess_exec", side_effect=patched_exec):
        results = await dispatch_run(
            tasks=tasks,
            concurrency=2,
            run_dir=run_dir,
            base_sha=base_sha,
            repo_root=e2e_repo,
            timeout=30,
            dashboard=dashboard,
            memory=memory,
        )

    done_count = sum(1 for r in results if r.status == "done")
    assert done_count == 2, f"Expected 2 done, got: {[(r.task_id, r.status, r.fail_reason) for r in results]}"

    # Both tasks should have commit SHAs
    for r in results:
        assert r.commit_sha is not None

    # Integration
    integration_sha = await integrate(
        tasks=tasks,
        run_dir=run_dir,
        base_sha=base_sha,
        repo_root=e2e_repo,
        dashboard=dashboard,
    )

    assert integration_sha != base_sha


@pytest.mark.asyncio
async def test_e2e_task_noop(e2e_repo: Path, fake_claude_noop: Path) -> None:
    """Task that makes no changes → noop status."""
    from cagent.dispatcher import run as dispatch_run
    from cagent.memory import RunMemory
    from cagent.progress import Dashboard
    from cagent.worktree import current_head

    run_dir = e2e_repo / ".cagent" / "runs" / "e2e-noop"
    run_dir.mkdir(parents=True)

    base_sha = current_head(e2e_repo)

    tasks = [
        Task(id="001", prompt="Do nothing", branch="cagent/e2e-noop/task-001"),
    ]
    dump_state(run_dir, tasks)

    dashboard = Dashboard(run_dir)
    memory = RunMemory(run_dir)

    orig_exec = asyncio.create_subprocess_exec

    async def patched_exec(*args, **kwargs):
        args_list = list(args)
        if args_list and args_list[0] == "claude":
            # Replace: claude -p - ... → python fake_claude_noop.py
            args_list = [sys.executable, str(fake_claude_noop)]
        return await orig_exec(*args_list, **kwargs)

    with patch("cagent.agent._resolve_claude", return_value="claude"), \
         patch("cagent.agent.prepare_sandbox"), \
         patch("cagent.agent.asyncio.create_subprocess_exec", side_effect=patched_exec):
        results = await dispatch_run(
            tasks=tasks,
            concurrency=1,
            run_dir=run_dir,
            base_sha=base_sha,
            repo_root=e2e_repo,
            timeout=30,
            dashboard=dashboard,
            memory=memory,
        )

    assert results[0].status == "noop"


@pytest.mark.asyncio
async def test_e2e_task_failure(e2e_repo: Path, fake_claude_fail: Path) -> None:
    """Task that fails → failed status with reason."""
    from cagent.dispatcher import run as dispatch_run
    from cagent.memory import RunMemory
    from cagent.progress import Dashboard
    from cagent.worktree import current_head

    run_dir = e2e_repo / ".cagent" / "runs" / "e2e-fail"
    run_dir.mkdir(parents=True)

    base_sha = current_head(e2e_repo)

    tasks = [
        Task(id="001", prompt="This will fail", branch="cagent/e2e-fail/task-001"),
    ]
    dump_state(run_dir, tasks)

    dashboard = Dashboard(run_dir)
    memory = RunMemory(run_dir)

    orig_exec = asyncio.create_subprocess_exec

    async def patched_exec(*args, **kwargs):
        args_list = list(args)
        if args_list and args_list[0] == "claude":
            args_list = [sys.executable, str(fake_claude_fail)]
        return await orig_exec(*args_list, **kwargs)

    with patch("cagent.agent._resolve_claude", return_value="claude"), \
         patch("cagent.agent.prepare_sandbox"), \
         patch("cagent.agent.asyncio.create_subprocess_exec", side_effect=patched_exec):
        results = await dispatch_run(
            tasks=tasks,
            concurrency=1,
            run_dir=run_dir,
            base_sha=base_sha,
            repo_root=e2e_repo,
            timeout=30,
            dashboard=dashboard,
            memory=memory,
        )

    assert results[0].status == "failed"
    assert "exited with code 1" in results[0].fail_reason


@pytest.mark.asyncio
async def test_e2e_dependency_chain(e2e_repo: Path, fake_claude: Path) -> None:
    """Tasks with dependencies are executed in correct order."""
    from cagent.dispatcher import run as dispatch_run
    from cagent.memory import RunMemory
    from cagent.progress import Dashboard
    from cagent.worktree import current_head

    run_dir = e2e_repo / ".cagent" / "runs" / "e2e-deps"
    run_dir.mkdir(parents=True)

    base_sha = current_head(e2e_repo)

    tasks = [
        Task(id="001", prompt="Create base FILE:base.py", branch="cagent/e2e-deps/task-001", depends_on=[]),
        Task(id="002", prompt="Create ext FILE:ext.py", branch="cagent/e2e-deps/task-002", depends_on=["001"]),
    ]
    dump_state(run_dir, tasks)

    dashboard = Dashboard(run_dir)
    memory = RunMemory(run_dir)

    orig_exec = asyncio.create_subprocess_exec

    async def patched_exec(*args, **kwargs):
        args_list = list(args)
        if args_list and args_list[0] == "claude":
            args_list = [sys.executable, str(fake_claude)]
        return await orig_exec(*args_list, **kwargs)

    with patch("cagent.agent._resolve_claude", return_value="claude"), \
         patch("cagent.agent.prepare_sandbox"), \
         patch("cagent.agent.asyncio.create_subprocess_exec", side_effect=patched_exec):
        results = await dispatch_run(
            tasks=tasks,
            concurrency=2,
            run_dir=run_dir,
            base_sha=base_sha,
            repo_root=e2e_repo,
            timeout=30,
            dashboard=dashboard,
            memory=memory,
        )

    # Both should succeed
    assert all(r.status == "done" for r in results), \
        f"Results: {[(r.task_id, r.status, r.fail_reason) for r in results]}"

    # Task 002 started after 001 (verify via dashboard timing)
    tp1 = dashboard.tasks.get("001")
    tp2 = dashboard.tasks.get("002")
    assert tp1 and tp2
    assert tp1.started_at is not None
    assert tp2.started_at is not None
    assert tp2.started_at >= tp1.ended_at or tp1.ended_at is None


@pytest.mark.asyncio
async def test_e2e_token_budget(e2e_repo: Path, fake_claude: Path) -> None:
    """Token budget enforcement stops dispatching new tasks."""
    from cagent.dispatcher import run as dispatch_run
    from cagent.memory import RunMemory
    from cagent.progress import Dashboard
    from cagent.worktree import current_head

    run_dir = e2e_repo / ".cagent" / "runs" / "e2e-budget"
    run_dir.mkdir(parents=True)

    base_sha = current_head(e2e_repo)

    tasks = [
        Task(id="001", prompt="Task A FILE:a.py", branch="cagent/e2e-budget/task-001"),
        Task(id="002", prompt="Task B FILE:b.py", branch="cagent/e2e-budget/task-002"),
        Task(id="003", prompt="Task C FILE:c.py", branch="cagent/e2e-budget/task-003"),
    ]
    dump_state(run_dir, tasks)

    dashboard = Dashboard(run_dir)
    memory = RunMemory(run_dir)

    orig_exec = asyncio.create_subprocess_exec

    async def patched_exec(*args, **kwargs):
        args_list = list(args)
        if args_list and args_list[0] == "claude":
            args_list = [sys.executable, str(fake_claude)]
        return await orig_exec(*args_list, **kwargs)

    with patch("cagent.agent._resolve_claude", return_value="claude"), \
         patch("cagent.agent.prepare_sandbox"), \
         patch("cagent.agent.asyncio.create_subprocess_exec", side_effect=patched_exec):
        results = await dispatch_run(
            tasks=tasks,
            concurrency=1,  # sequential so budget check works between tasks
            run_dir=run_dir,
            base_sha=base_sha,
            repo_root=e2e_repo,
            timeout=30,
            dashboard=dashboard,
            memory=memory,
            max_tokens=200,  # very low budget — first task uses 150 tokens
        )

    # At least one task should have been budget-stopped
    budget_failed = [r for r in results if r.fail_reason and "budget" in r.fail_reason]
    done = [r for r in results if r.status == "done"]
    assert len(done) >= 1
    assert len(budget_failed) >= 1
